extends RefCounted

# Single source of defaults, UI metadata, bounds and import validation.
const ITEMS := [
	{"group":"生存压力","id":"instinct_strength","label":"本能强度（低 / 标准 / 高）","value":1.0,"min":0.5,"max":1.5,"step":0.5,"unit":"倍","help":"0.5 低 / 1 标准 / 1.5 高；只有运动偏移，玩家始终可以反向抵抗。","developer":false},
	{"group":"开发调参","id":"instinct_start_threshold","label":"instinct_start_threshold","value":35.0,"min":10.0,"max":60.0,"step":1.0,"unit":"倍","help":"0.5 低 / 1 标准 / 1.5 高；只有运动偏移，玩家始终可以反向抵抗。","developer":true},
	{"group":"开发调参","id":"instinct_max_strength","label":"instinct_max_strength","value":0.35,"min":0.0,"max":0.45,"step":0.01,"unit":"倍","help":"0.5 低 / 1 标准 / 1.5 高；只有运动偏移，玩家始终可以反向抵抗。","developer":true},
	{"group":"生存压力","id":"hunger_enabled","label":"饥饿系统","value":true,"help":"不进食会降低饱食度和体力恢复，极饿时产生可抵抗的觅食偏移。"},
	{"group":"开发调参","id":"satiety_start","label":"satiety_start","value":100.0,"min":0.0,"max":100.0,"step":1.0,"unit":"","help":"Phase 1 physiology tuning; default decay calibrated from 1000-seed median 40.90 seconds.","developer":true},
	{"group":"开发调参","id":"satiety_decay","label":"satiety_decay","value":2.445,"min":0.0,"max":10.0,"step":0.001,"unit":"","help":"Phase 1 physiology tuning; default decay calibrated from 1000-seed median 40.90 seconds.","developer":true},
	{"group":"开发调参","id":"satiety_low_threshold","label":"satiety_low_threshold","value":60.0,"min":20.0,"max":90.0,"step":1.0,"unit":"","help":"Phase 1 physiology tuning; default decay calibrated from 1000-seed median 40.90 seconds.","developer":true},
	{"group":"开发调参","id":"satiety_critical_threshold","label":"satiety_critical_threshold","value":25.0,"min":5.0,"max":50.0,"step":1.0,"unit":"","help":"Phase 1 physiology tuning; default decay calibrated from 1000-seed median 40.90 seconds.","developer":true},
	{"group":"开发调参","id":"satiety_starving_threshold","label":"satiety_starving_threshold","value":10.0,"min":0.0,"max":20.0,"step":1.0,"unit":"","help":"Phase 1 physiology tuning; default decay calibrated from 1000-seed median 40.90 seconds.","developer":true},
	{"group":"开发调参","id":"satiety_food_value","label":"satiety_food_value","value":2.0,"min":0.0,"max":10.0,"step":0.1,"unit":"","help":"Phase 1 physiology tuning; default decay calibrated from 1000-seed median 40.90 seconds.","developer":true},
	{"group":"开发调参","id":"satiety_recovery_min","label":"satiety_recovery_min","value":0.35,"min":0.1,"max":1.0,"step":0.05,"unit":"","help":"Phase 1 physiology tuning; default decay calibrated from 1000-seed median 40.90 seconds.","developer":true},
	{"group":"回合","id":"food_goal","label":"挑战食物目标","value":60.0,"min":1.0,"max":120.0,"step":1.0,"unit":"点","help":"固定地图共四团饵，总目标不能高于全部饵料收益。"},
	{"group":"回合","id":"practice_goal","label":"练习食物目标","value":18.0,"min":1.0,"max":120.0,"step":1.0,"unit":"点","help":"练习模式回巢所需食物。"},
	{"group":"回合","id":"time_limit","label":"挑战时间","value":360.0,"min":30.0,"max":1800.0,"step":10.0,"unit":"秒","help":"对战超时鱼获胜；鱼单人挑战超时失败。"},
	{"group":"回合","id":"home_hold","label":"回巢停留时间","value":2.0,"min":0.2,"max":10.0,"step":0.1,"unit":"秒","help":"满足食物条件后在巢穴内保持停留。"},
	{"group":"体力","id":"stamina_max","label":"体力上限","value":100.0,"min":10.0,"max":1000.0,"step":10.0,"unit":"点","help":"体力条、疲劳、AI 与抄网统一按此上限计算。"},
	{"group":"体力","id":"stamina_initial","label":"初始体力比例","value":1.0,"min":0.0,"max":1.0,"step":0.05,"unit":"比例","help":"新一局体力等于上限乘此比例。"},
	{"group":"体力","id":"stamina_recovery","label":"自然恢复","value":18.0,"min":0.0,"max":100.0,"step":1.0,"unit":"点/秒","help":"停止耗力并经过恢复延迟后生效。"},
	{"group":"体力","id":"stamina_delay","label":"恢复延迟","value":0.55,"min":0.0,"max":5.0,"step":0.05,"unit":"秒","help":"冲刺或抗线消耗后，等待多久开始恢复。"},
	{"group":"体力","id":"sprint_drain","label":"冲刺消耗","value":28.0,"min":0.0,"max":150.0,"step":1.0,"unit":"点/秒","help":"持续冲刺的体力消耗；设为零不耗体力。"},
	{"group":"体力","id":"resist_drain","label":"抗线消耗","value":11.0,"min":0.0,"max":100.0,"step":1.0,"unit":"点/秒","help":"完全逆拉力游动的消耗，按抗拉程度缩放。"},
	{"group":"体力","id":"food_recovery","label":"进食恢复","value":4.0,"min":0.0,"max":30.0,"step":0.5,"unit":"点/食物","help":"每获得一点食物恢复的体力。"},
	{"group":"体力","id":"sprint_restart","label":"冲刺恢复门槛","value":0.2,"min":0.05,"max":1.0,"step":0.05,"unit":"比例","help":"耗尽后松开加速，并恢复至此比例才能再冲刺。"},
	{"group":"体力","id":"fatigue_threshold","label":"疲劳门槛","value":0.2,"min":0.05,"max":1.0,"step":0.05,"unit":"比例","help":"上钩后低于此体力比例，游速逐渐降低。"},
	{"group":"体力","id":"fatigue_speed","label":"耗尽时速度倍率","value":0.4,"min":0.1,"max":1.0,"step":0.05,"unit":"倍","help":"上钩且体力为零时，仍能游动的速度比例。"},
	{"group":"游动","id":"swim_speed","label":"常速","value":70.0,"min":15.0,"max":180.0,"step":5.0,"unit":"像素/秒","help":"鱼的正常游动速度，AI 同步适应。"},
	{"group":"游动","id":"slow_speed","label":"慢游速度","value":26.0,"min":5.0,"max":100.0,"step":1.0,"unit":"像素/秒","help":"按 Q 慢游的速度。"},
	{"group":"游动","id":"sprint_speed","label":"冲刺速度","value":140.0,"min":30.0,"max":280.0,"step":5.0,"unit":"像素/秒","help":"按住鼠标右键冲刺的速度。"},
	{"group":"游动","id":"swim_accel","label":"游动加速度","value":330.0,"min":50.0,"max":1200.0,"step":10.0,"unit":"像素/秒²","help":"越大越快达到目标速度。"},
	{"group":"游动","id":"sprint_accel","label":"冲刺加速度","value":650.0,"min":50.0,"max":1800.0,"step":10.0,"unit":"像素/秒²","help":"冲刺起步的响应。"},
	{"group":"游动","id":"feeding_speed","label":"吸食游速倍率","value":0.68,"min":0.1,"max":1.0,"step":0.01,"unit":"倍","help":"吸食时的游速比例，慢游和冲刺同样生效；松开吸食后恢复。"},
	{"group":"饵与吸食","id":"suction_range","label":"吸食距离","value":44.0,"min":12.0,"max":90.0,"step":1.0,"unit":"像素","help":"锥形吸食区域的前向长度。"},
	{"group":"饵与吸食","id":"suction_mouth","label":"锥体近端半宽","value":4.0,"min":1.0,"max":12.0,"step":0.5,"unit":"像素","help":"鱼嘴前吸食区域的起始半宽。"},
	{"group":"饵与吸食","id":"suction_spread","label":"锥体扩张率","value":0.53,"min":0.1,"max":1.0,"step":0.01,"unit":"倍","help":"每向前一像素，半宽增加的像素数。"},
	{"group":"饵与吸食","id":"suction_initial","label":"默认吸力","value":0.35,"min":0.1,"max":1.0,"step":0.05,"unit":"比例","help":"每局开始时吸力，局内仍可用滚轮调整。"},
	{"group":"饵与吸食","id":"pellet_speed","label":"颗粒吸入速度","value":95.0,"min":20.0,"max":250.0,"step":5.0,"unit":"像素/秒","help":"满吸力时的颗粒吸入速度；轻吸时较慢。"},
	{"group":"饵与吸食","id":"pellet_detach","label":"饵粒剥落速度","value":4.5,"min":0.5,"max":15.0,"step":0.5,"unit":"倍","help":"轻吸更容易剥落外层；猛吸加速内层和核心的剥落。"},
	{"group":"饵与吸食","id":"pellet_rate","label":"最大剥落速率","value":28.0,"min":2.0,"max":80.0,"step":1.0,"unit":"粒/秒","help":"满吸力时的最大剥落速率；轻吸时较少。"},
	{"group":"饵与吸食","id":"bait_points","label":"每团饵食物量","value":30.0,"min":5.0,"max":100.0,"step":1.0,"unit":"点","help":"只改变收益，保留精细的小颗粒造型。"},
	{"group":"饵与吸食","id":"hook_scale","label":"鱼钩外观尺寸","value":0.7,"min":0.35,"max":1.2,"step":0.05,"unit":"倍","help":"调整鱼钩绘制大小；咬钩接触范围单独调整。"},
	{"group":"饵与吸食","id":"bite_radius","label":"咬钩接触半径","value":7.0,"min":2.0,"max":15.0,"step":0.5,"unit":"像素","help":"钩尖靠近鱼嘴到此距离，会进入吐钩 QTE。"},
	{"group":"饵与吸食","id":"hook_suction","label":"饵团吸动倍率","value":1.0,"min":0.0,"max":3.0,"step":0.1,"unit":"倍","help":"钩饵和散饵整团向鱼嘴移动的幅度；两类饵料共用相同吸力响应。"},
	{"group":"饵与吸食","id":"hook_immunity","label":"脱钩后保护时间","value":1.8,"min":0.1,"max":8.0,"step":0.1,"unit":"秒","help":"避免刚脱钩立即再次咬钩。"},
	{"group":"饵与吸食","id":"bait_cycle","label":"换饵等待","value":30.0,"min":5.0,"max":120.0,"step":1.0,"unit":"秒","help":"单人挑战中固定饵料的轮换等待。"},
	{"group":"饵与吸食","id":"bait_refill","label":"换饵间隔","value":5.0,"min":0.5,"max":30.0,"step":0.5,"unit":"秒","help":"收走饵料后，下一团饵投入前的等待。"},
	{"group":"收放线","id":"angler_speed","label":"鱼竿左右移动速度","value":72.0,"min":20.0,"max":180.0,"step":2.0,"unit":"像素/秒","help":"影响岸上操作和鱼线惯性。"},
	{"group":"收放线","id":"reel_speed","label":"手动收线速度","value":36.0,"min":5.0,"max":120.0,"step":1.0,"unit":"像素/秒","help":"W 的基础收线速度，发力 QTE 可短暂改变它。"},
	{"group":"收放线","id":"release_speed","label":"手动放线速度","value":90.0,"min":10.0,"max":240.0,"step":5.0,"unit":"像素/秒","help":"S 的放线速度。"},
	{"group":"收放线","id":"line_response","label":"收放线响应倍率","value":1.0,"min":0.25,"max":3.0,"step":0.05,"unit":"倍","help":"咬钩前后都生效；越大越快调整线速。"},
	{"group":"收放线","id":"line_force","label":"鱼线牵引倍率","value":1.0,"min":0.0,"max":3.0,"step":0.05,"unit":"倍","help":"零为关闭牵引，方便练习；不改变抄网。"},
	{"group":"收放线","id":"line_pull","label":"最大拉拽速度","value":65.0,"min":10.0,"max":160.0,"step":5.0,"unit":"像素/秒","help":"满张力下鱼被线牵引的基础速度。"},
	{"group":"收放线","id":"auto_reel","label":"自动收线基础速度","value":24.0,"min":0.0,"max":80.0,"step":1.0,"unit":"像素/秒","help":"AI 持续收线的基础速度。"},
	{"group":"收放线","id":"auto_release","label":"自动放线限速","value":24.0,"min":5.0,"max":120.0,"step":1.0,"unit":"像素/秒","help":"AI 高张力时的最大放线速度。"},
	{"group":"收放线","id":"auto_gain","label":"自动张力响应","value":100.0,"min":20.0,"max":300.0,"step":5.0,"unit":"系数","help":"AI 偏离目标张力时调整线速的强度。"},
	{"group":"收放线","id":"auto_tension","label":"自动目标张力","value":0.5,"min":0.15,"max":0.85,"step":0.01,"unit":"比例","help":"AI 自动收放线围绕此张力调整。"},
	{"group":"收放线","id":"line_elastic","label":"鱼线弹性行程","value":32.0,"min":8.0,"max":96.0,"step":1.0,"unit":"像素","help":"同样拉长距离产生的张力；越大越柔软。"},
	{"group":"收放线","id":"line_max","label":"上钩鱼线最大长度","value":720.0,"min":300.0,"max":1200.0,"step":10.0,"unit":"像素","help":"被鱼拉出后允许的总长度上限。"},
	{"group":"收放线","id":"line_free_max","label":"未上钩最大放线","value":520.0,"min":180.0,"max":900.0,"step":10.0,"unit":"像素","help":"不超过上钩后的总长度上限。"},
	{"group":"收放线","id":"cast_depth","label":"初始下钩长度","value":132.0,"min":60.0,"max":230.0,"step":1.0,"unit":"像素","help":"Q 下钩时的竖直投放距离。"},
	{"group":"张力与逃脱","id":"tension_low","label":"松线张力门槛","value":0.25,"min":0.05,"max":0.8,"step":0.01,"unit":"比例","help":"低于此值持续一段时间，出现脱钩机会。"},
	{"group":"张力与逃脱","id":"slack_hold","label":"松线机会等待","value":0.5,"min":0.1,"max":10.0,"step":0.1,"unit":"秒","help":"连续低张力多久开始松线脱钩 QTE。"},
	{"group":"张力与逃脱","id":"tension_high","label":"断线张力门槛","value":0.9,"min":0.1,"max":1.0,"step":0.01,"unit":"比例","help":"需高于松线门槛至少 5%，才会累计断线时间。"},
	{"group":"张力与逃脱","id":"break_hold","label":"持续拉断线时间","value":3.0,"min":0.2,"max":30.0,"step":0.1,"unit":"秒","help":"高张力持续到此时间会断线；回落后重新计时。"},
	{"group":"张力与逃脱","id":"slack_retry","label":"脱钩失败冷却","value":1.2,"min":0.1,"max":10.0,"step":0.1,"unit":"秒","help":"松线判定失败或张力回升后的等待。"},
	{"group":"张力与逃脱","id":"landing_hold","label":"拉出水确认时间","value":0.65,"min":0.1,"max":5.0,"step":0.05,"unit":"秒","help":"未缠线的鱼被拉到岸边后，持续多久开始提鱼。"},
	{"group":"张力与逃脱","id":"landing_lift","label":"提鱼出水时间","value":1.05,"min":0.3,"max":4.0,"step":0.05,"unit":"秒","help":"拉出水的动画与结算时长。"},
	{"group":"缠线与解线","id":"wrap_seconds","label":"缠绕动画时长","value":0.85,"min":0.3,"max":3.0,"step":0.05,"unit":"秒","help":"鱼绕障碍物与线圈同步完成。"},
	{"group":"缠线与解线","id":"wrap_retry","label":"缠线失败冷却","value":1.2,"min":0.1,"max":10.0,"step":0.1,"unit":"秒","help":"离开障碍物或判定失败后的等待。"},
	{"group":"缠线与解线","id":"wrap_slack","label":"缠线获得松弛长度","value":9.0,"min":0.0,"max":30.0,"step":1.0,"unit":"像素","help":"成功缠绕后，鱼端额外获得的线长。"},
	{"group":"缠线与解线","id":"wrap_pull","label":"缠线后拉力倍率","value":0.5,"min":0.1,"max":1.0,"step":0.05,"unit":"倍","help":"障碍物减轻传到鱼端的拉力。"},
	{"group":"缠线与解线","id":"wrap_spool","label":"缠线后收放效率","value":0.22,"min":0.05,"max":1.0,"step":0.01,"unit":"倍","help":"有线圈时，渔轮收放传到鱼端的比例。"},
	{"group":"缠线与解线","id":"untangle_min","label":"解线最低张力","value":0.25,"min":0.05,"max":0.85,"step":0.01,"unit":"比例","help":"解线判定时必须在此值与最高值之间。"},
	{"group":"缠线与解线","id":"untangle_max","label":"解线最高张力","value":0.55,"min":0.1,"max":0.95,"step":0.01,"unit":"比例","help":"不能低于最低值加 5%。"},
	{"group":"缠线与解线","id":"unwind_seconds","label":"解线动画时长","value":0.7,"min":0.3,"max":3.0,"step":0.05,"unit":"秒","help":"成功后线圈退开的时间，保留现有动画。"},
	{"group":"缠线与解线","id":"untangle_cooldown","label":"解线冷却","value":3.0,"min":0.5,"max":15.0,"step":0.5,"unit":"秒","help":"两次解线尝试之间的最短间隔。"},
	{"group":"缠线与解线","id":"untangle_force","label":"解线时拉力倍率","value":0.55,"min":0.1,"max":1.0,"step":0.05,"unit":"倍","help":"解线判定和退圈期间人的发力比例。"},
	{"group":"缠线与解线","id":"untangle_recover","label":"解线失败脱力时间","value":0.75,"min":0.1,"max":5.0,"step":0.05,"unit":"秒","help":"失败后维持短暂脱力的时间。"},
	{"group":"抄网","id":"net_scale","label":"网口尺寸倍率","value":1.0,"min":0.5,"max":1.5,"step":0.05,"unit":"倍","help":"网口显示、警示、碰撞、捕获范围同步缩放。"},
	{"group":"抄网","id":"net_manual_warning","label":"手动抄网预警","value":0.5,"min":0.1,"max":3.0,"step":0.05,"unit":"秒","help":"提交两点路线后的入水预警；鱼仍可移动。"},
	{"group":"抄网","id":"net_manual_speed","label":"手动抄网速度","value":160.0,"min":40.0,"max":300.0,"step":5.0,"unit":"像素/秒","help":"网口沿已锁定的两点路线移动的速度。"},
	{"group":"抄网","id":"net_cooldown","label":"抄网观察冷却","value":6.0,"min":2.0,"max":40.0,"step":1.0,"unit":"秒","help":"两次手动抄网之间的等待。"},
	{"group":"抄网","id":"net_first","label":"首次自动抄网等待","value":18.0,"min":3.0,"max":90.0,"step":1.0,"unit":"秒","help":"鱼单人模式第一次抄网的等待。"},
	{"group":"抄网","id":"net_interval","label":"自动抄网间隔","value":35.0,"min":5.0,"max":120.0,"step":1.0,"unit":"秒","help":"后续自动抄网间隔。"},
	{"group":"抄网","id":"net_observe_time","label":"观察时限","value":2.5,"min":0.8,"max":6.0,"step":0.1,"unit":"秒","help":"进入水下视角后选两点的时间，超时也冷却。"},
	{"group":"抄网","id":"net_reach","label":"抄网可达距离","value":340.0,"min":180.0,"max":620.0,"step":10.0,"unit":"像素","help":"起点与终点均不能超出钓鱼人竿端的可达范围。"},
	{"group":"抄网","id":"net_sight","label":"水下观察距离","value":380.0,"min":180.0,"max":680.0,"step":10.0,"unit":"像素","help":"鱼影随距离减淡，超过范围不可见。"},
	{"group":"抄网","id":"net_min_path","label":"最短扫掠距离","value":30.0,"min":15.0,"max":100.0,"step":5.0,"unit":"像素","help":"两点间至少保持的距离。"},
	{"group":"抄网","id":"net_max_path","label":"最长扫掠距离","value":200.0,"min":50.0,"max":400.0,"step":10.0,"unit":"像素","help":"超出距离时预览与实际终点共同截短。"},
	{"group":"抄网","id":"net_push","label":"网边推力","value":85.0,"min":0.0,"max":200.0,"step":5.0,"unit":"像素/秒","help":"每次扫网最多推开同一条鱼一次。"},
	{"group":"抄网","id":"net_slow_time","label":"擦网减速时长","value":0.35,"min":0.0,"max":1.0,"step":0.05,"unit":"秒","help":"侧面擦网后的短暂减速时间，仍可操作。"},
	{"group":"抄网","id":"net_slow_factor","label":"擦网速度倍率","value":0.7,"min":0.3,"max":1.0,"step":0.05,"unit":"倍","help":"擦网后的游速比例，随后恢复。"},
	{"group":"环境与AI","id":"water_strength","label":"水流强度","value":1.0,"min":0.0,"max":4.0,"step":0.1,"unit":"倍","help":"同时影响鱼、鱼钩、饵粒和水流表现。"},
	{"group":"环境与AI","id":"vegetation_speed","label":"水草中速度倍率","value":0.68,"min":0.2,"max":1.0,"step":0.01,"unit":"倍","help":"穿过水草时的阻力。"},
	{"group":"环境与AI","id":"cover_opacity","label":"接触障碍物透明度","value":0.68,"min":0.3,"max":1.0,"step":0.01,"unit":"不透明比例","help":"越接近一越不透明，不改变能否穿过。"},
	{"group":"环境与AI","id":"ai_entry_skill","label":"鱼AI吐钩成功率","value":0.42,"min":0.0,"max":1.0,"step":0.01,"unit":"比例","help":"AI 仍通过同一套 QTE 输入判断。"},
	{"group":"环境与AI","id":"ai_escape_skill","label":"鱼AI逃脱判定成功率","value":0.68,"min":0.0,"max":1.0,"step":0.01,"unit":"比例","help":"松线脱钩和缠线判定的预期成功率。"},
	{"group":"环境与AI","id":"ai_effort_skill","label":"AI发力与解线成功率","value":0.72,"min":0.0,"max":1.0,"step":0.01,"unit":"比例","help":"还需满足相同的张力等条件。"},
	{"group":"环境与AI","id":"ai_reaction","label":"鱼AI上钩反应时间","value":0.85,"min":0.0,"max":3.0,"step":0.05,"unit":"秒","help":"从咬钩到开始主动抗拉的等待。"},
	{"group":"回合","id":"timer_enabled","label":"挑战启用倒计时","value":true,"unit":"","help":"关闭后不因超时结算，仍能进食回巢或捕获。"},
	{"group":"QTE·入口吐钩","id":"qte_entry_lead","label":"提示后准备时间","value":0.4,"min":0.0,"max":2.0,"step":0.05,"unit":"秒","help":"提示音后等待多久开始移动浮漂。"},
	{"group":"QTE·入口吐钩","id":"qte_entry_sweep","label":"指针走完整轨时长","value":2.0,"min":0.5,"max":8.0,"step":0.05,"unit":"秒","help":"越大越慢，不改变成功区的实际秒数。"},
	{"group":"QTE·入口吐钩","id":"qte_entry_window","label":"成功区停留时间","value":0.24,"min":0.04,"max":2.0,"step":0.01,"unit":"秒","help":"绿区长度由此时间除以整轨时长计算，上限为轨道的 80%。"},
	{"group":"QTE·入口吐钩","id":"qte_entry_random","label":"随机成功区位置","value":true,"unit":"","help":"每次开始判定时随机选择；关闭后采用固定位置。"},
	{"group":"QTE·入口吐钩","id":"qte_entry_zone","label":"固定成功区起点","value":0.6,"min":0.1,"max":0.88,"step":0.01,"unit":"轨道比例","help":"仅关闭随机位置时生效；自动留出完整成功区。"},
	{"group":"QTE·松线脱钩","id":"qte_slack_lead","label":"提示后准备时间","value":0.4,"min":0.0,"max":2.0,"step":0.05,"unit":"秒","help":"提示音后等待多久开始移动浮漂。"},
	{"group":"QTE·松线脱钩","id":"qte_slack_sweep","label":"指针走完整轨时长","value":2.0,"min":0.5,"max":8.0,"step":0.05,"unit":"秒","help":"越大越慢，不改变成功区的实际秒数。"},
	{"group":"QTE·松线脱钩","id":"qte_slack_window","label":"成功区停留时间","value":0.24,"min":0.04,"max":2.0,"step":0.01,"unit":"秒","help":"绿区长度由此时间除以整轨时长计算，上限为轨道的 80%。"},
	{"group":"QTE·松线脱钩","id":"qte_slack_random","label":"随机成功区位置","value":true,"unit":"","help":"每次开始判定时随机选择；关闭后采用固定位置。"},
	{"group":"QTE·松线脱钩","id":"qte_slack_zone","label":"固定成功区起点","value":0.6,"min":0.1,"max":0.88,"step":0.01,"unit":"轨道比例","help":"仅关闭随机位置时生效；自动留出完整成功区。"},
	{"group":"QTE·缠线","id":"qte_wrap_lead","label":"提示后准备时间","value":0.4,"min":0.0,"max":2.0,"step":0.05,"unit":"秒","help":"提示音后等待多久开始移动浮漂。"},
	{"group":"QTE·缠线","id":"qte_wrap_sweep","label":"指针走完整轨时长","value":2.0,"min":0.5,"max":8.0,"step":0.05,"unit":"秒","help":"越大越慢，不改变成功区的实际秒数。"},
	{"group":"QTE·缠线","id":"qte_wrap_window","label":"成功区停留时间","value":0.24,"min":0.04,"max":2.0,"step":0.01,"unit":"秒","help":"绿区长度由此时间除以整轨时长计算，上限为轨道的 80%。"},
	{"group":"QTE·缠线","id":"qte_wrap_random","label":"随机成功区位置","value":true,"unit":"","help":"每次开始判定时随机选择；关闭后采用固定位置。"},
	{"group":"QTE·缠线","id":"qte_wrap_zone","label":"固定成功区起点","value":0.6,"min":0.1,"max":0.88,"step":0.01,"unit":"轨道比例","help":"仅关闭随机位置时生效；自动留出完整成功区。"},
	{"group":"QTE·鱼发力","id":"qte_fish_effort_lead","label":"提示后准备时间","value":0.4,"min":0.0,"max":2.0,"step":0.05,"unit":"秒","help":"提示音后等待多久开始移动浮漂。"},
	{"group":"QTE·鱼发力","id":"qte_fish_effort_sweep","label":"指针走完整轨时长","value":2.0,"min":0.5,"max":8.0,"step":0.05,"unit":"秒","help":"越大越慢，不改变成功区的实际秒数。"},
	{"group":"QTE·鱼发力","id":"qte_fish_effort_window","label":"成功区停留时间","value":0.2,"min":0.04,"max":2.0,"step":0.01,"unit":"秒","help":"绿区长度由此时间除以整轨时长计算，上限为轨道的 80%。"},
	{"group":"QTE·鱼发力","id":"qte_fish_effort_random","label":"随机成功区位置","value":true,"unit":"","help":"每次开始判定时随机选择；关闭后采用固定位置。"},
	{"group":"QTE·鱼发力","id":"qte_fish_effort_zone","label":"固定成功区起点","value":0.6,"min":0.1,"max":0.88,"step":0.01,"unit":"轨道比例","help":"仅关闭随机位置时生效；自动留出完整成功区。"},
	{"group":"QTE·鱼发力","id":"fish_effort_frequency","label":"发力触发频率","value":1.0,"min":0.25,"max":3.0,"step":0.05,"unit":"倍","help":"持续发力时累计等待；一倍通常间隔 3–12 秒。"},
	{"group":"QTE·鱼发力","id":"fish_effort_boost","label":"成功加力倍率","value":1.35,"min":1.05,"max":2.5,"step":0.05,"unit":"倍","help":"短暂增加有效发力。"},
	{"group":"QTE·鱼发力","id":"fish_effort_weak","label":"失败剩余力度","value":0.6,"min":0.1,"max":1.0,"step":0.05,"unit":"倍","help":"越小失败后的脱力越明显。"},
	{"group":"QTE·鱼发力","id":"fish_effort_boost_seconds","label":"成功加力时间","value":2.0,"min":0.2,"max":6.0,"step":0.1,"unit":"秒","help":"加力效果保持的时间。"},
	{"group":"QTE·鱼发力","id":"fish_effort_weak_seconds","label":"失败脱力时间","value":1.5,"min":0.2,"max":6.0,"step":0.1,"unit":"秒","help":"脱力效果保持的时间。"},
	{"group":"QTE·人发力","id":"qte_angler_effort_lead","label":"提示后准备时间","value":0.4,"min":0.0,"max":2.0,"step":0.05,"unit":"秒","help":"提示音后等待多久开始移动浮漂。"},
	{"group":"QTE·人发力","id":"qte_angler_effort_sweep","label":"指针走完整轨时长","value":2.0,"min":0.5,"max":8.0,"step":0.05,"unit":"秒","help":"越大越慢，不改变成功区的实际秒数。"},
	{"group":"QTE·人发力","id":"qte_angler_effort_window","label":"成功区停留时间","value":0.2,"min":0.04,"max":2.0,"step":0.01,"unit":"秒","help":"绿区长度由此时间除以整轨时长计算，上限为轨道的 80%。"},
	{"group":"QTE·人发力","id":"qte_angler_effort_random","label":"随机成功区位置","value":true,"unit":"","help":"每次开始判定时随机选择；关闭后采用固定位置。"},
	{"group":"QTE·人发力","id":"qte_angler_effort_zone","label":"固定成功区起点","value":0.6,"min":0.1,"max":0.88,"step":0.01,"unit":"轨道比例","help":"仅关闭随机位置时生效；自动留出完整成功区。"},
	{"group":"QTE·人发力","id":"angler_effort_frequency","label":"发力触发频率","value":1.0,"min":0.25,"max":3.0,"step":0.05,"unit":"倍","help":"持续发力时累计等待；一倍通常间隔 3–12 秒。"},
	{"group":"QTE·人发力","id":"angler_effort_boost","label":"成功加力倍率","value":1.35,"min":1.05,"max":2.5,"step":0.05,"unit":"倍","help":"短暂增加有效发力。"},
	{"group":"QTE·人发力","id":"angler_effort_weak","label":"失败剩余力度","value":0.6,"min":0.1,"max":1.0,"step":0.05,"unit":"倍","help":"越小失败后的脱力越明显。"},
	{"group":"QTE·人发力","id":"angler_effort_boost_seconds","label":"成功加力时间","value":2.0,"min":0.2,"max":6.0,"step":0.1,"unit":"秒","help":"加力效果保持的时间。"},
	{"group":"QTE·人发力","id":"angler_effort_weak_seconds","label":"失败脱力时间","value":1.5,"min":0.2,"max":6.0,"step":0.1,"unit":"秒","help":"脱力效果保持的时间。"},
	{"group":"QTE·解线","id":"qte_untangle_lead","label":"提示后准备时间","value":0.4,"min":0.0,"max":2.0,"step":0.05,"unit":"秒","help":"提示音后等待多久开始移动浮漂。"},
	{"group":"QTE·解线","id":"qte_untangle_sweep","label":"指针走完整轨时长","value":2.0,"min":0.5,"max":8.0,"step":0.05,"unit":"秒","help":"越大越慢，不改变成功区的实际秒数。"},
	{"group":"QTE·解线","id":"qte_untangle_window","label":"成功区停留时间","value":0.2,"min":0.04,"max":2.0,"step":0.01,"unit":"秒","help":"绿区长度由此时间除以整轨时长计算，上限为轨道的 80%。"},
	{"group":"QTE·解线","id":"qte_untangle_random","label":"随机成功区位置","value":true,"unit":"","help":"每次开始判定时随机选择；关闭后采用固定位置。"},
	{"group":"QTE·解线","id":"qte_untangle_zone","label":"固定成功区起点","value":0.6,"min":0.1,"max":0.88,"step":0.01,"unit":"轨道比例","help":"仅关闭随机位置时生效；自动留出完整成功区。"}
]
